import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Nav from '@components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Principles that form a magical Computer Science era',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='main-container'>
          <div className='gradient' />
        </div>
        <main className='app'>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
